### ISSUE TITLE
Consider changing the name of the project to a string without dot (.)

### ISSUE THREAD

**Issue by grzanka** [freespace/pylecroy#1]
After doing `git clone https://github.com/freespace/lecroy.py.git` I get a directory with `.` in a name which suggests that this is a file.

@freespace can you do it before I submit a PR ?

**Comment by freespace** [comment]
Any suggestions? I I agree the dot can be annoying.

**Comment by grzanka** [comment]
pylecroy ?

**Comment by freespace** [comment]
Heh I had the same thought. Now to work out if I can rename the repo.

**Comment by freespace** [comment]
Turns out you can pretty easily. Done.
