### ISSUE TITLE
Indent the file according to PEP8 rules

### ISSUE THREAD

**Issue by grzanka** [freespace/pylecroy#4]

**Comment by freespace** [comment]
Hrmph, on one hand I don't like 4 spaces for indentation b/c it uses 2 spaces too many. OTOH since this project is now no longer my personal play ground standards can't hurt.

I am out of my allocated 'not-thesis-writing' time for today however, so I will get back to this when I can.

**Comment by grzanka** [comment]
Anyway thanks for investing your time in making this piece of code open !
I will put some effort in next days to improve this tool a bit, but everything will go with slower pace and via issues & PR.
Good luck with your thesis !

**Comment by freespace** [comment]
No worries. I will have some more time tomorrow to work on this :)
